### ISSUE TITLE
Request: `npm install` should use the `--production` flag

### ISSUE THREAD

**Issue by msluther** [godaddy/carpenterd#64]
The `npm install` that `carpenterd` does [here](https://github.com/godaddy/carpenterd/blob/12315890c15f010d8345e6ff713a2e4cf86085d9/lib/construct/npm/index.js#L30-L34) should be done with a `--production` flag passed.

Pros:

1. This will speed up build as less will need to be installed
1. This will decrease the size each tarball (and thus storage costs) for each version

Cons:

1. Potentially breaking for any package that doesn't have the right breakdown in dependencies vs dev-dependencies.
1. Work arounds for stopping the automatic creation of dependent-packages will stop working (those packages are actually needed at build time, but you don't always want to be a dependent build).

**Comment by msluther** [comment]
We could make it optional to avoid the break, but the dependent build issue would still exist.

My inclination is to fix this after making dependent builds explicit (can't find the issue for this) and then to do a major bump of carpenterd where we always pass `--production` with npm-install

**Comment by msluther** [comment]
We'd also have to have a way to deal with having the compiler (and its components) to get shipped since they're typically in devDependencies (e.g. `webpack` & `webpack-cli`)

**Comment by Swaagie** [comment]
This feels like the removal of a feature IMHO, e.g. removing the ability to specify the exact version of the bundler you want to use. Initially we forcefully did builds through our available `webpack@1` (at that time), but it blocked us and partner teams from being able to update packages to say `webpack@2` one at a time. Obviously we can code around this and allow all different webpack versions to be JIT installed based on some semver that is specified. But why take that burden if `npm` can do it for us?

**Comment by msluther** [comment]
Yeah, I'd forgotten about the build-aspect of this at first. With that context remembered, We could probably do _something_, but probably far more trouble than it's worth and would force packages to do unnatural things (like putting stuff in optional-dependencies, etc).  If npm had something like `devDependencies` vs `buildDependencies` I think we could make a stronger argument for something.

Going to close out this issue since I agree that carpenterd shouldn't really do this ever..
